// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __Localization_hh__
#define __Localization_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Localization
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Localization
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Localization
#endif



#ifndef __OpenHRPCommon_hh_EXTERNAL_GUARD__
#define __OpenHRPCommon_hh_EXTERNAL_GUARD__
#include <OpenHRPCommon.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE OpenHRP

_CORBA_MODULE_BEG

#ifndef __OpenHRP_mLocalization__
#define __OpenHRP_mLocalization__

  class Localization;
  class _objref_Localization;
  class _impl_Localization;
  
  typedef _objref_Localization* Localization_ptr;
  typedef Localization_ptr LocalizationRef;

  class Localization_Helper {
  public:
    typedef Localization_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Localization, Localization_Helper> Localization_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Localization,Localization_Helper > Localization_out;

#endif

  // interface Localization
  class Localization {
  public:
    // Declarations for this interface type.
    typedef Localization_ptr _ptr_type;
    typedef Localization_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Localization :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    void getLocalizationForLink(const char* aLinkName, ::OpenHRP::LinkPosition& aLinkPosition);

    inline _objref_Localization()  { _PR_setobj(0); }  // nil
    _objref_Localization(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Localization();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Localization(const _objref_Localization&);
    _objref_Localization& operator = (const _objref_Localization&);
    // not implemented

    friend class Localization;
  };

  class _pof_Localization : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Localization() : _OMNI_NS(proxyObjectFactory)(Localization::_PD_repoId) {}
    virtual ~_pof_Localization();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Localization :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Localization();

    virtual void getLocalizationForLink(const char* aLinkName, ::OpenHRP::LinkPosition& aLinkPosition) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_OpenHRP
_CORBA_MODULE_BEG

  class Localization :
    public virtual OpenHRP::_impl_Localization,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Localization();

    inline ::OpenHRP::Localization_ptr _this() {
      return (::OpenHRP::Localization_ptr) _do_this(::OpenHRP::Localization::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_OpenHRP
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
OpenHRP::Localization::_marshalObjRef(::OpenHRP::Localization_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Localization
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Localization
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Localization
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Localization
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Localization
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Localization
#endif

#endif  // __Localization_hh__

