// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "Localization.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



OpenHRP::Localization_ptr OpenHRP::Localization_Helper::_nil() {
  return ::OpenHRP::Localization::_nil();
}

::CORBA::Boolean OpenHRP::Localization_Helper::is_nil(::OpenHRP::Localization_ptr p) {
  return ::CORBA::is_nil(p);

}

void OpenHRP::Localization_Helper::release(::OpenHRP::Localization_ptr p) {
  ::CORBA::release(p);
}

void OpenHRP::Localization_Helper::marshalObjRef(::OpenHRP::Localization_ptr obj, cdrStream& s) {
  ::OpenHRP::Localization::_marshalObjRef(obj, s);
}

OpenHRP::Localization_ptr OpenHRP::Localization_Helper::unmarshalObjRef(cdrStream& s) {
  return ::OpenHRP::Localization::_unmarshalObjRef(s);
}

void OpenHRP::Localization_Helper::duplicate(::OpenHRP::Localization_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

OpenHRP::Localization_ptr
OpenHRP::Localization::_duplicate(::OpenHRP::Localization_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

OpenHRP::Localization_ptr
OpenHRP::Localization::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


OpenHRP::Localization_ptr
OpenHRP::Localization::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

OpenHRP::Localization_ptr
OpenHRP::Localization::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Localization _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Localization* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_Localization;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* OpenHRP::Localization::_PD_repoId = "IDL:OpenHRP/Localization:1.0";


OpenHRP::_objref_Localization::~_objref_Localization() {
  
}


OpenHRP::_objref_Localization::_objref_Localization(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::OpenHRP::Localization::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
OpenHRP::_objref_Localization::_ptrToObjRef(const char* id)
{
  if( id == ::OpenHRP::Localization::_PD_repoId )
    return (::OpenHRP::Localization_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::OpenHRP::Localization::_PD_repoId) )
    return (::OpenHRP::Localization_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring_o_cOpenHRP_mLinkPosition
class _0RL_cd_5eedc2f9c208a004_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5eedc2f9c208a004_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  OpenHRP::LinkPosition arg_1_;
  OpenHRP::LinkPosition* arg_1;
};

void _0RL_cd_5eedc2f9c208a004_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_5eedc2f9c208a004_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_5eedc2f9c208a004_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const OpenHRP::LinkPosition&) *arg_1 >>= _n;

}

void _0RL_cd_5eedc2f9c208a004_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (OpenHRP::LinkPosition&)*arg_1 <<= _n;

}

const char* const _0RL_cd_5eedc2f9c208a004_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5eedc2f9c208a004_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5eedc2f9c208a004_00000000* tcd = (_0RL_cd_5eedc2f9c208a004_00000000*)cd;
  OpenHRP::_impl_Localization* impl = (OpenHRP::_impl_Localization*) svnt->_ptrToInterface(OpenHRP::Localization::_PD_repoId);
  impl->getLocalizationForLink(tcd->arg_0, *tcd->arg_1);


}

void OpenHRP::_objref_Localization::getLocalizationForLink(const char* aLinkName, ::OpenHRP::LinkPosition& aLinkPosition)
{
  _0RL_cd_5eedc2f9c208a004_00000000 _call_desc(_0RL_lcfn_5eedc2f9c208a004_10000000, "getLocalizationForLink", 23);
  _call_desc.arg_0 = aLinkName;
  _call_desc.arg_1 = &(::OpenHRP::LinkPosition&) aLinkPosition;

  _invoke(_call_desc);



}
OpenHRP::_pof_Localization::~_pof_Localization() {}


omniObjRef*
OpenHRP::_pof_Localization::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::OpenHRP::_objref_Localization(ior, id);
}


::CORBA::Boolean
OpenHRP::_pof_Localization::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::OpenHRP::Localization::_PD_repoId) )
    return 1;
  
  return 0;
}

const OpenHRP::_pof_Localization _the_pof_OpenHRP_mLocalization;

OpenHRP::_impl_Localization::~_impl_Localization() {}


::CORBA::Boolean
OpenHRP::_impl_Localization::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "getLocalizationForLink") ) {

    _0RL_cd_5eedc2f9c208a004_00000000 _call_desc(_0RL_lcfn_5eedc2f9c208a004_10000000, "getLocalizationForLink", 23, 1);
    _call_desc.arg_1 = &_call_desc.arg_1_;
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
OpenHRP::_impl_Localization::_ptrToInterface(const char* id)
{
  if( id == ::OpenHRP::Localization::_PD_repoId )
    return (::OpenHRP::_impl_Localization*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::OpenHRP::Localization::_PD_repoId) )
    return (::OpenHRP::_impl_Localization*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
OpenHRP::_impl_Localization::_mostDerivedRepoId()
{
  return ::OpenHRP::Localization::_PD_repoId;
}

POA_OpenHRP::Localization::~Localization() {}

